### ISSUE TITLE
consider installing the 'firewalld' package as a part of this role

### ISSUE THREAD

**Issue by robled** [oasis-roles/firewalld#11]
Some images may not have the **firewalld** package installed out of the box, so we should consider having this role install it if not already present.

**Comment by greg-hellings** [comment]
Oh goodness, I thought that was already here. Yes x 4.

**Comment by dmc5179** [comment]
Seems like this issue has been resolved?

**Comment by tutunak** [comment]
@robled Can you close this issue?. I see that changes in your role.
